image: python

stages:
  - test
  - package

before_script:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install -r requirements/test.txt

py34-django-20:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-django-20

py35-django-20:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-django-20

py35-django-21:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-django-21

py36-django-20:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-django-20

py36-django-21:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-django-21

flake8:
  image: python:3.6
  stage: test
  script:
    - tox -e flake8

dist:
  image: python:3.6
  stage: package
  only:
    - tags
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - "dist/*"
