# Generated by Django 2.1.4 on 2019-01-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_breakfasts', '0004_auto_20190104_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dj_breakfasts.Participant', unique_for_date='date'),
        ),
    ]
