# Generated by Django 2.1.4 on 2018-12-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Breakfast creation date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Breakfast creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Breakfast last modification date')),
            ],
            options={
                'verbose_name': 'Breakfast date',
                'verbose_name_plural': 'Breakfast dates',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='First name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last modification date')),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.AddField(
            model_name='breakfast',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakfasts.Participant', unique_for_date='date'),
        ),
    ]
