# Generated by Django 2.1.4 on 2019-01-24 17:17

import breakfasts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[breakfasts.validators.date_is_future], verbose_name='date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('email_task_id', models.CharField(blank=True, editable=False, max_length=255, verbose_name='email task id')),
                ('next_breakfast_task_id', models.CharField(blank=True, editable=False, max_length=255, verbose_name='next breakfast task id')),
            ],
            options={
                'verbose_name': 'breakfast',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='first name')),
                ('last_name', models.CharField(max_length=128, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modification date')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'participant',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.AddField(
            model_name='breakfast',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='breakfasts.Participant', unique_for_date='date'),
        ),
    ]
