# Generated by Django 2.1.4 on 2019-01-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfasts', '0002_participant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='email_task_id',
            field=models.CharField(default='', editable=False, max_length=255, verbose_name='Breakfast task_id'),
            preserve_default=False,
        ),
    ]
