# Generated by Django 2.1.4 on 2019-01-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfasts', '0003_breakfast_email_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='email_task_id',
            field=models.CharField(max_length=255, verbose_name='Breakfast task_id'),
        ),
    ]
