# Generated by Django 2.1.4 on 2019-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfasts', '0005_auto_20190107_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='breakfast creation date'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(verbose_name='breakfast creation date'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='email_task_id',
            field=models.CharField(max_length=255, verbose_name='breakfast task_id'),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='breakfast last modification date'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification date'),
        ),
    ]
