# Generated by Django 2.1.4 on 2019-01-18 16:09

import breakfasts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakfasts', '0006_auto_20190117_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='date',
            field=models.DateField(validators=[breakfasts.validators.date_is_future], verbose_name='breakfast creation date'),
        ),
    ]
